apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
resources:
  # Sourcegraph Main Stack
  - ../../../base/sourcegraph
  # Monitoring Stack
  - ../../../base/monitoring
components:
  - ../../../components/monitoring/cadvisor
  - ../../../components/sizes/m
  - ../../../components/privileged
  - ../../../components/monitoring/privileged
  - ../../../components/enable/service-discovery
