apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
resources:
  # Sourcegraph Main Stack
  - ../../../base/sourcegraph
components:
  # Monitoring Stack
  - ../../../components/monitoring
  # Use resources for a size-L instance
  - ../../../components/sizes/l
  - ../../../components/clusters/gke/configure
