# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: codeintel-db
# spec:
#   template:
#     spec:
#       initContainers:
#         - name: correct-data-dir-permissions
#           securityContext:
#             allowPrivilegeEscalation: false
#             runAsGroup: 999
#             runAsUser: 999
#       containers:
#         - name: pgsql
#           securityContext:
#             allowPrivilegeEscalation: false
#             runAsUser: 999
#             runAsGroup: 999
#       securityContext:
#         fsGroup: 999
#         runAsUser: 999
